### ISSUE TITLE
Don't order user to prefix a custom variable when it's written to a file

### ISSUE THREAD

**Issue by Cogitri** [maxice8/meltryllis#3]
E.g. in the networkmanager APKBUILD the following is written:
```
	cat > $pkgdir/usr/share/doc/$pkgname/README.alpine <<EOF
To modify system network connections without the root password: add your user account to the 'plugdev' group, or use Polkit.

To use iwd instead of the default wpa_supplicant install iwd, start its service and the following to your /etc/NetworkManager/NetworkManager.conf:

[device]
wifi.backend=iwd
EOF
```

This triggers alint: `community/networkmanager/APKBUILD:105: prefix custom variable with _: wifi.backend=iwd`

**Comment by maxice8** [comment]
Sadly this is impossible, we check against anything in the global scope, the easiest solution is to use `<<-` and indent it, sorry.
